name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    run-tests:
        runs-on: ubuntu-latest

        steps:
            # this checks out the repo
          - name: checkout the code
            uses: actions/checkout@v3
            
            # this installs pnpm (latest version. should this be changed since node is on 23?)
          - name: Setup pnpm
            uses: pnpm/action-setup@v4
            with:
                version: 'latest'

            # this intalls node.js (version 23, just what i have on my machine rn)
          - name: Setup Node.js
            uses: actions/setup-node@v3
            with:
                node-version: '23'
            
            # this installs the dependencies with pnpm
          - name: install dependencies
            run: pnpm install
          
            # this installs the foundry toolchain. Needed because the tests use `anvil`
          - name: install foundry
            uses: foundry-rs/foundry-toolchain@v1
            
            # finally, this runs the tests with a basic `pnpm test` command
          - name: run tests
            run: pnpm test
